# Generated by Django 3.0.7 on 2020-06-20 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('asistencia', models.CharField(choices=[('No-asistio', 'No asistio'), ('Asistio', 'Asistio')], max_length=100)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.Alumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia del alumno',
                'verbose_name_plural': 'Asistencia de los alumnos',
                'ordering': ['alumno'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Examen', 'Examen'), ('Exposicion', 'Exposicion'), ('Parcial', 'Parcial')], max_length=50)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.Asistencia')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.Curso')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['nota'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.Asistencia')),
            ],
            options={
                'verbose_name': 'Justificación',
                'verbose_name_plural': 'Justificaciones de las asistencias',
            },
        ),
    ]
