# Generated by Django 3.0.7 on 2020-06-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asistencia',
            field=models.CharField(choices=[('Asistio', 'Asistio'), ('No-asistio', 'No asistio')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('Examen', 'Examen'), ('Parcial', 'Parcial'), ('Exposicion', 'Exposicion')], max_length=50),
        ),
    ]
