# Generated by Django 3.0.7 on 2020-06-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0004_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='nota',
            field=models.IntegerField(null=True),
        ),
    ]
