# Generated by Django 3.0.7 on 2020-06-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0004_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asistencia',
            field=models.CharField(choices=[('Asistio', 'Asistio'), ('No-asistio', 'No asistio')], max_length=100),
        ),
    ]
